-- Run this in the Supabase SQL Editor to create the missing table

CREATE TABLE IF NOT EXISTS public.card_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES public.credit_cards_details(id),
    bank_name TEXT,
    card_name TEXT,
    local_filename TEXT,
    scraper_image_url TEXT,
    manual_image_url TEXT,
    scraper_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    image_url TEXT, -- This is where we will store the final Public URL
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Optional: Create an index on card_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_card_images_card_id ON public.card_images(card_id);
