-- Create card_inventory
CREATE TABLE IF NOT EXISTS public.card_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE,
    bank_name TEXT,
    first_discovered_date TEXT,
    last_verified_date TEXT,
    is_active BOOLEAN,
    card_name TEXT
);

-- Create llm_interaction_log
CREATE TABLE IF NOT EXISTS public.llm_interaction_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_url TEXT,
    bank_name TEXT,
    card_name TEXT,
    run_timestamp TEXT,
    raw_page_text TEXT,
    llm_response_json TEXT,
    status TEXT
);
